from Client.pages.admin_page import AdminPage
from Client.pages.login_page import LoginPage
from Client.pages.sign_up_page import SignUpPage
from Client.pages.battle import BattlePage
from Client.pages.code import Codes
from Client.pages.battle import BattlePage
from Client.pages.tournament import TournamentPage
from Client.pages.group_management import GroupManagementPage
from Client.pages.code import CodePage